---
language: go
go:
  - "1.16"

env:
  matrix:
    - MAKE_TASK="lintall travis-lint gosec scan-nancy"

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - pip --quiet install yamllint
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
  - go get github.com/securego/gosec/cmd/gosec
  - go get github.com/sonatype-nexus-community/nancy

script:
  - make $MAKE_TASK

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

jobs:
  include:
    - stage: unit tests
      script:
        - test/run-tests.sh ; [[ "$?" == "0" ]] || (travis_terminate 1)
      if: type = pull_request or type = push
