---
language: go
go:
  - "1.16"

env:
  matrix:
    - MAKE_TASK="travis-lint"

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - pip --quiet install yamllint

script:
  - make $MAKE_TASK

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
jobs:
  include:
    - stage: unit tests
      script:
        - test/run-tests.sh ; [[ "$?" == "0" ]] || (travis_terminate 1)
      if: type = pull_request or type = push
