package protocol

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *ForwardMessage) Msgsize() (s int) {
	s = 1 + msgp.StringPrefixSize + len(z.Tag) + z.Entries.Msgsize()
	if z.Options == nil {
		s += msgp.NilSize
	} else {
		s += z.Options.Msgsize()
	}
	return
}
