// Code generated by counterfeiter. DO NOT EDIT.
package clientfakes

import (
	"sync"

	"github.com/IBM/fluent-forward-go/fluent/client"
	"github.com/tinylib/msgp/msgp"
)

type FakeWSClientFactory struct {
	ConnectStub        func() error
	connectMutex       sync.RWMutex
	connectArgsForCall []struct {
	}
	connectReturns struct {
		result1 error
	}
	connectReturnsOnCall map[int]struct {
		result1 error
	}
	DisconnectStub        func() error
	disconnectMutex       sync.RWMutex
	disconnectArgsForCall []struct {
	}
	disconnectReturns struct {
		result1 error
	}
	disconnectReturnsOnCall map[int]struct {
		result1 error
	}
	ReconnectStub        func() error
	reconnectMutex       sync.RWMutex
	reconnectArgsForCall []struct {
	}
	reconnectReturns struct {
		result1 error
	}
	reconnectReturnsOnCall map[int]struct {
		result1 error
	}
	SendMessageStub        func(msgp.Encodable) error
	sendMessageMutex       sync.RWMutex
	sendMessageArgsForCall []struct {
		arg1 msgp.Encodable
	}
	sendMessageReturns struct {
		result1 error
	}
	sendMessageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWSClientFactory) Connect() error {
	fake.connectMutex.Lock()
	ret, specificReturn := fake.connectReturnsOnCall[len(fake.connectArgsForCall)]
	fake.connectArgsForCall = append(fake.connectArgsForCall, struct {
	}{})
	stub := fake.ConnectStub
	fakeReturns := fake.connectReturns
	fake.recordInvocation("Connect", []interface{}{})
	fake.connectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWSClientFactory) ConnectCallCount() int {
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	return len(fake.connectArgsForCall)
}

func (fake *FakeWSClientFactory) ConnectCalls(stub func() error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = stub
}

func (fake *FakeWSClientFactory) ConnectReturns(result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	fake.connectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) ConnectReturnsOnCall(i int, result1 error) {
	fake.connectMutex.Lock()
	defer fake.connectMutex.Unlock()
	fake.ConnectStub = nil
	if fake.connectReturnsOnCall == nil {
		fake.connectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.connectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) Disconnect() error {
	fake.disconnectMutex.Lock()
	ret, specificReturn := fake.disconnectReturnsOnCall[len(fake.disconnectArgsForCall)]
	fake.disconnectArgsForCall = append(fake.disconnectArgsForCall, struct {
	}{})
	stub := fake.DisconnectStub
	fakeReturns := fake.disconnectReturns
	fake.recordInvocation("Disconnect", []interface{}{})
	fake.disconnectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWSClientFactory) DisconnectCallCount() int {
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	return len(fake.disconnectArgsForCall)
}

func (fake *FakeWSClientFactory) DisconnectCalls(stub func() error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = stub
}

func (fake *FakeWSClientFactory) DisconnectReturns(result1 error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = nil
	fake.disconnectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) DisconnectReturnsOnCall(i int, result1 error) {
	fake.disconnectMutex.Lock()
	defer fake.disconnectMutex.Unlock()
	fake.DisconnectStub = nil
	if fake.disconnectReturnsOnCall == nil {
		fake.disconnectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.disconnectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) Reconnect() error {
	fake.reconnectMutex.Lock()
	ret, specificReturn := fake.reconnectReturnsOnCall[len(fake.reconnectArgsForCall)]
	fake.reconnectArgsForCall = append(fake.reconnectArgsForCall, struct {
	}{})
	stub := fake.ReconnectStub
	fakeReturns := fake.reconnectReturns
	fake.recordInvocation("Reconnect", []interface{}{})
	fake.reconnectMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWSClientFactory) ReconnectCallCount() int {
	fake.reconnectMutex.RLock()
	defer fake.reconnectMutex.RUnlock()
	return len(fake.reconnectArgsForCall)
}

func (fake *FakeWSClientFactory) ReconnectCalls(stub func() error) {
	fake.reconnectMutex.Lock()
	defer fake.reconnectMutex.Unlock()
	fake.ReconnectStub = stub
}

func (fake *FakeWSClientFactory) ReconnectReturns(result1 error) {
	fake.reconnectMutex.Lock()
	defer fake.reconnectMutex.Unlock()
	fake.ReconnectStub = nil
	fake.reconnectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) ReconnectReturnsOnCall(i int, result1 error) {
	fake.reconnectMutex.Lock()
	defer fake.reconnectMutex.Unlock()
	fake.ReconnectStub = nil
	if fake.reconnectReturnsOnCall == nil {
		fake.reconnectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reconnectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) SendMessage(arg1 msgp.Encodable) error {
	fake.sendMessageMutex.Lock()
	ret, specificReturn := fake.sendMessageReturnsOnCall[len(fake.sendMessageArgsForCall)]
	fake.sendMessageArgsForCall = append(fake.sendMessageArgsForCall, struct {
		arg1 msgp.Encodable
	}{arg1})
	stub := fake.SendMessageStub
	fakeReturns := fake.sendMessageReturns
	fake.recordInvocation("SendMessage", []interface{}{arg1})
	fake.sendMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeWSClientFactory) SendMessageCallCount() int {
	fake.sendMessageMutex.RLock()
	defer fake.sendMessageMutex.RUnlock()
	return len(fake.sendMessageArgsForCall)
}

func (fake *FakeWSClientFactory) SendMessageCalls(stub func(msgp.Encodable) error) {
	fake.sendMessageMutex.Lock()
	defer fake.sendMessageMutex.Unlock()
	fake.SendMessageStub = stub
}

func (fake *FakeWSClientFactory) SendMessageArgsForCall(i int) msgp.Encodable {
	fake.sendMessageMutex.RLock()
	defer fake.sendMessageMutex.RUnlock()
	argsForCall := fake.sendMessageArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeWSClientFactory) SendMessageReturns(result1 error) {
	fake.sendMessageMutex.Lock()
	defer fake.sendMessageMutex.Unlock()
	fake.SendMessageStub = nil
	fake.sendMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) SendMessageReturnsOnCall(i int, result1 error) {
	fake.sendMessageMutex.Lock()
	defer fake.sendMessageMutex.Unlock()
	fake.SendMessageStub = nil
	if fake.sendMessageReturnsOnCall == nil {
		fake.sendMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeWSClientFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.connectMutex.RLock()
	defer fake.connectMutex.RUnlock()
	fake.disconnectMutex.RLock()
	defer fake.disconnectMutex.RUnlock()
	fake.reconnectMutex.RLock()
	defer fake.reconnectMutex.RUnlock()
	fake.sendMessageMutex.RLock()
	defer fake.sendMessageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWSClientFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.WSClientFactory = new(FakeWSClientFactory)
